site_name: myl7's Blog
site_url: https://myl.moe
site_description: myl7's blog
site_author: Yulong Ming (myl7)
repo_url: https://github.com/myl7/mylmoe
copyright: >-
  Copyright (C) 2024 Yulong Ming (myl7).
  Posts licensed under CC BY 4.0, unless otherwise stated.
theme:
  name: material
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - blog:
      blog_dir: .
      categories_allowed: []
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
nav:
  - Friends: friends.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.blocks.caption
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/myl7
    - icon: fontawesome/brands/telegram
      link: https://t.me/myl7s
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=J9cpSb0AAAAJ
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-6010-2661
extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
