site_name: myl7's Blog
site_url: https://myl.moe
site_description: myl7's blog
site_author: Yulong Ming (myl7)
repo_url: https://github.com/myl7/mylmoe
copyright: >-
  Copyright (C) 2024 Yulong Ming (myl7).
  Posts licensed under CC BY 4.0, unless otherwise stated.
theme:
  name: material
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - blog:
      blog_dir: "."
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/myl7
    - icon: fontawesome/brands/telegram
      link: https://t.me/myl7s
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=J9cpSb0AAAAJ
